git:
    depth: 1
sudo: false
cache:
    directories:
        - $HOME/.composer/cache
language: php
php:
    - '7.0'
    - '7.1'
install:
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
before_script:
    - composer install --prefer-dist -o --no-scripts
script:
    - ./vendor/bin/phpunit